#!/usr/bin/env bash
# submit_pr.sh OWNER REPO FIXES_JSON_FILE
set -e

OWNER="$1"; REPO="$2"; FIXES_FILE="$3"
MY_GITHUB_USER=$(gh api user | jq -r '.login')
BRANCH="security/auto-fix-$(date +%Y%m%d)"

TP_COUNT=$(jq '[.[] | select(.false_positive==false and .fix_available==true)] | length' "$FIXES_FILE")
[ "$TP_COUNT" -eq 0 ] && echo "No actionable findings — skipping PR" && exit 0

echo "[pr] Forking ${OWNER}/${REPO}..."
gh repo fork "${OWNER}/${REPO}" --clone=false

TMPDIR=$(mktemp -d)
git clone "https://github.com/${MY_GITHUB_USER}/${REPO}" "$TMPDIR"
cd "$TMPDIR"

git remote add upstream "https://github.com/${OWNER}/${REPO}"
git fetch upstream --quiet
UPSTREAM_BRANCH=$(git remote show upstream | grep 'HEAD branch' | awk '{print $NF}')
git checkout -b "$BRANCH" "upstream/${UPSTREAM_BRANCH}"

echo "[pr] Applying $(jq '[.[] | select(.false_positive==false and .fix_available==true)] | length' <<<$(cat "$FIXES_FILE")) patches..."
jq -c '.[] | select(.false_positive==false and .fix_available==true)' "$FIXES_FILE" | \
while IFS= read -r finding; do
  PATCH=$(echo "$finding" | jq -r '.patch_unified_diff')
  TITLE=$(echo "$finding" | jq -r '.title')
  echo "$PATCH" | git apply --index 2>/dev/null && \
    git commit -m "security: fix ${TITLE}" --quiet || \
    echo "[pr] Patch failed for: $TITLE"
done

git push origin "$BRANCH" --quiet

PR_BODY=$(python3 - "$FIXES_FILE" <<'PYEOF'
import sys, json
fixes = json.load(open(sys.argv[1]))
tps = [f for f in fixes if not f['false_positive'] and f['fix_available']]
lines = [
    "## Automated Security Findings\n",
    "This PR was generated by an automated security scanner. "
    "All findings were verified as true positives before submission.\n",
    f"**{len(tps)} issue(s) addressed:**\n",
]
for i, f in enumerate(tps, 1):
    sev_emoji = {"CRITICAL":"🔴","HIGH":"🟠","MEDIUM":"🟡"}.get(f['severity'],'⚪')
    lines.append(f"\n### {i}. {sev_emoji} [{f['severity']}] {f['title']}")
    lines.append(f"- **File:** `{f['file']}` line {f['line_start']}")
    lines.append(f"- **Type:** {f['type']} | **CVSS:** {f['cvss_score']}")
    lines.append(f"- **CWE:** {f.get('cwe','N/A')}")
    lines.append(f"\n{f['pr_explanation']}")
    lines.append(f"\n**Remediation:** {f['remediation']}\n")
lines.append("\n---")
lines.append("*This PR was submitted by an automated security scanner. "
             "If you believe any finding is a false positive, please close the PR with a comment.*")
print('\n'.join(lines))
PYEOF
)

PR_RESULT=$(gh pr create \
  --repo "${OWNER}/${REPO}" \
  --title "[Security] Automated vulnerability fixes — $(date +%Y-%m-%d)" \
  --body "$PR_BODY" \
  --label "security" \
  --head "${MY_GITHUB_USER}:${BRANCH}" 2>&1)

echo "$PR_RESULT"

cd ~ && rm -rf "$TMPDIR"
